repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: __init__.py
        args: [ --profile, black, --filter-files ]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        exclude: __init__.py
        args: [--py310-plus]


-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8
        exclude: __init__.py

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: __init__.py

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        exclude: __init__.py

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      exclude: __init__.py
      language_version: python3.10
      args: [--line-length=79]
